//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filamentous.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filamentous.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Components_Layout_CultureSelector_en_US {
            get {
                return ResourceManager.GetString("Components_Layout_CultureSelector_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Components_Layout_CultureSelector_es_US {
            get {
                return ResourceManager.GetString("Components_Layout_CultureSelector_es-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Components_Layout_CultureSelector_fr_FR {
            get {
                return ResourceManager.GetString("Components_Layout_CultureSelector_fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filamentous.Web (en).
        /// </summary>
        public static string Components_Layout_MainLayout_Header {
            get {
                return ResourceManager.GetString("Components_Layout_MainLayout_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Components_Layout_MainLayout_Reload {
            get {
                return ResourceManager.GetString("Components_Layout_MainLayout_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        public static string Components_Layout_MainLayout_UnhandledError {
            get {
                return ResourceManager.GetString("Components_Layout_MainLayout_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Components_Layout_NavMenu_Brands {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Components_Layout_NavMenu_Home {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Types.
        /// </summary>
        public static string Components_Layout_NavMenu_ImageTypes {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_ImageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Components_Layout_NavMenu_Login {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Components_Layout_NavMenu_Logout {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polymers.
        /// </summary>
        public static string Components_Layout_NavMenu_Polymers {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_Polymers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Components_Layout_NavMenu_Register {
            get {
                return ResourceManager.GetString("Components_Layout_NavMenu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the polymer named {0}?.
        /// </summary>
        public static string Components_Polymers_List_DeleteText {
            get {
                return ResourceManager.GetString("Components_Polymers_List_DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Polymer?.
        /// </summary>
        public static string Components_Polymers_List_DeleteTitle {
            get {
                return ResourceManager.GetString("Components_Polymers_List_DeleteTitle", resourceCulture);
            }
        }
    }
}
